spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://cosmos2.ck3sdux3veh4.ap-northeast-2.rds.amazonaws.com:3306/cosmos2
    username: root
    password: ekdlseotmd

mybatis:
  mapper-locations: classpath*:mapper/*.xml